server:
  port: 8070

spring:
  application:
    name: "book-store-account"

  profiles:
    active: dev

#  data:
#    redis:
#      host: 133.186.241.167
#      port: 6379
#      password: ${REDIS_PASSWORD}
#      database: 24

  jwt:
    secret: 33085d3cf14717d13f122979944e1e886636cc19e0f749dfbce423bb0031beae8b8758243ce109259c32a83a9325ef2c64433bc0339321d9540036a11884f8fc
    access-token:
      expires-in: 600000
    refresh-token:
      expires-in: 86400000

springdoc:
  api-docs:
    path: /auth-api
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /auth-api.html
    disable-swagger-default-url: true

logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR

oritang:
  redis:
    host: 4c4a07c6d57c41cba23cf12de6c87559
    port: 0de6a31493de4282830c2dab83e7264c
    password: d9b767e1131b4434b75d1fb52444ee1e
    database: 63bd8d5b9fe046058cedd2feb66fc253
